### ISSUE TITLE
wish: display key "facebook"

### ISSUE THREAD

**Issue by promeneur** [Qwant/qwantmaps#112]
Many shops or else have not any website but  have a facebook page.
Many shops or else have a website for general purpose and facebook for news.

There is a key "facebook" for this.

It is useful to display also the facebook page.

Thanks

**Comment by amatissart** [comment]
The `facebook` tag is supposed to be used as a website URL already, if neither `website` nor `contact:website` tag has been found.

Have you noticed any shop or other point of interest where it's not the case ?

**Comment by promeneur** [comment]
i understand if there is no website and there is a facebook page then you display the facebook url. right ?

But if there is a website and a facebook page it is useful to display the web site url and the facebook url because website is for general purpose and facebook is for news to maintain a link with customers.

**Comment by promeneur** [comment]
I made an error.

If there is no website and there is a facebook page then facebook page url is not displayed.

We need facebook url. It is very useful.

**Comment by promeneur** [comment]
An example

"coffret de saveurs" 
188 Avenue Louis Barthou
33200 Bordeaux

https://www.facebook.com/coffretdesaveurs

**Comment by i-need-to-tell-you-something** [comment]
The above example as a [Qwant Maps link](https://www.qwant.com/maps/place/osm:node:6225598248@Coffret_de_Saveurs#map=16.50/44.8522733/-0.6188506). Seems to be displaying correctly now?

**Comment by i-need-to-tell-you-something** [comment]
I also think that all the `contact:*=`(and their duplicates like `facebook=` fields should always be displayed irrespective of whether there is a `contact:website=` or `website=` because different users have different preferences. Someone might care about Instagram, someone might prefer Facebook, someone wants their email. UI wise they can be separate or change <kbd>Website</kbd> to <kbd>Websites</kbd> if there are multiple (Instagram, Facebook, etc).

**Comment by promeneur** [comment]
@i-need-to-tell-you-something

I agree with this. The website and Facebook page must be displayed, not the sole website or the sole Facebook page.

An example where only the website is displayed
 https://www.qwant.com/maps/place/osm:node:310212089@Pharmacie_de_Lestonnat#map=16.50/44.8522733/-0.6188506

**Comment by Charlotte-Ziegler** [comment]
Good news! The key "Facebook" is now available on our POIs.
