### ISSUE TITLE
"Your position" is way off on desktop

### ISSUE THREAD

**Issue by mhatvan** [Qwant/qwantmaps#125]
First of all, thank you for this great tool, I enjoy using it a lot and it has great user experience!

## Issue
When I choose "your position" to GPS track me, it works perfectly on the phone.

On desktop PC without GPS capabilities, "your position" finds my location to be somewhere 10km off.

Should position estimating work on desktop devices too? If not, hiding it would probably be a good idea.

**Comment by i-need-to-tell-you-something** [comment]
I'm fairly certain it works the same way for you on Google Maps as well. 

I believe many desktop users are familiar with how much off their position is on a desktop browser without GPS. Thus, personally, I don't feel it should be hidden.
