### ISSUE TITLE
Street names not match in Brazil

### ISSUE THREAD

**Issue by gustavo22soars** [Qwant/qwantmaps#126]
street names of addresses do not match with OpenStreetMap data in Brazil many are in capslock and without accent that already has on many streets
this is an orthographic problem of the address database
https://www.qwant.com/maps/place/latlon:-5.32108:-44.24349#map=18.87/-5.3207867/-44.2433876

**Comment by gustavo22soars** [comment]
![image](https://user-images.githubusercontent.com/69773290/92997081-d3208280-f4e6-11ea-979e-2ec43836151f.png)

**Comment by amatissart** [comment]
Thanks for your feedback. The addresses used on Qwant Maps are either directly extracted from OpenStreetMap data or imported from [OpenAddresses](https://openaddresses.io/), a collection of open datasets of addresses around the world.  

In this case, the area does not seem to contain any address in OSM, so we are completely dependent on the quality of the data provided by the OpenAddresses project. I would suggest you to raise the issue on [its own GitHub repository](https://github.com/openaddresses/openaddresses), possibly with a reliable source for properly formatted data : https://github.com/openaddresses/openaddresses
