### ISSUE TITLE
Prioritise relevant results in currently viewed area

### ISSUE THREAD

**Issue by lzambarda** [Qwant/qwantmaps#129]
Hello there!
If there are multiple results for a query (i.e. a chain of shops), it can be daunting to find the one in the currently viewed area on the map.
One could also argue that results outside it or in other countries should not even appear in the results!

**Comment by Charlotte-Ziegler** [comment]
Hello, 
I confirm that we are already doing that. The suggested results prioritize the currently displayed area.
