### ISSUE TITLE
Can't select nameless points of interest

### ISSUE THREAD

**Issue by dpalacio** [Qwant/qwantmaps#139]
In some minor towns, businesses may not feel the need to name themselves, they only have their place. This is a problem in Qwant because I can't tap on one nameless point and check its information or possibly get navigation directions to it.

Place with name selected:
![Screenshot_20210329-125849](https://user-images.githubusercontent.com/12900/112879348-a1d86000-908e-11eb-985b-b3beadcc951a.png)
https://www.qwant.com/maps/place/osm:node:8402762798@Mi_Taberna#map=19.47/10.3925787/-73.0264235

Place without name can't be selected:
![Screenshot_20210329-125906](https://user-images.githubusercontent.com/12900/112879471-cb918700-908e-11eb-8be2-d44e04811a80.png)

Browser: Vivaldi in Android 3.7

**Comment by i-need-to-tell-you-something** [comment]
Can confirm. Example nameless POI [here](https://www.qwant.com/maps/place/latlon:58.34889:26.73985#map=20.00/58.3489338/26.7400554) if zooming in.

**Comment by Charlotte-Ziegler** [comment]
Thank you for this issue and I'm glad to announce that it was corrected.
