### ISSUE TITLE
3D building rendering support

### ISSUE THREAD

**Issue by Cucazer** [Qwant/qwantmaps#140]
I've recently discovered that viewpoint panning is possible with RMB. However, all buildings in the view remained flat.

Can rendering using [Simple 3D Buildings](https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings)  schema be implemented?

**Comment by Charlotte-Ziegler** [comment]
Hello
Thanks for this idea, it sounds great and we will keep this option in mind. 
However I'm sorry this is not planed into our product roadmap for this year.

Thanks for your input!
