### ISSUE TITLE
"Display all results" behaves in a slightly confusing way

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [Qwant/qwantmaps#143]
# How to reproduce:
1. Be viewing a place that has sports centers.
2. Click on the <kbd>Sport</kbd> category filter button:

![image](https://user-images.githubusercontent.com/9165395/116130905-6ef8aa80-a6d4-11eb-99e0-829e13bdbfdd.png)
3. Zoom in on one of the sports facilities until you can't see others anymore.
4. Click on the sports facility (either on the map or in the items list panel on the left)
5. Click on the <kbd>Display all results</kbd> button:

![image](https://user-images.githubusercontent.com/9165395/116130596-17f2d580-a6d4-11eb-86f9-4d1a5b04b587.png)

# Observed:

Only that single sports facility displayed:

![image](https://user-images.githubusercontent.com/9165395/116130750-41136600-a6d4-11eb-900e-194be2b18d90.png)

# Expected:
To see more than one - because the button label is <kbd>Display **ALL** results</kbd> (plural) and because recently I saw multiple features of that type displayed.

# Ideas:
#### Easy fixes:
1. Ignore this edge case. (Although this did happen to me naturally and I was confused for a moment)
2. Rename the button <kbd>Display all results</kbd> to one of the following:
<kbd>Display all nearby results</kbd> or 
<kbd>Display all results in the area</kbd> or more clearly:
<kbd>Display all results in current view</kbd> or
<kbd>Display all results in current viewport</kbd>
If this fits on mobile screens as well.

#### Harder fix:
3. Intelligently guess how much to zoom out to show relevant other features of the selected type (sports centers in this case). Not too little, not too much. Or just always do the same - e.g. 5km x 5km or 10km x 10km.

**Comment by Charlotte-Ziegler** [comment]
Hello, 
I close this issue because I think this behavior does not exist anymore. 

Thank you for your contribution.
