### ISSUE TITLE
Save zoom level in the current address

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [Qwant/qwantmaps#144]
# How to reproduce:

1. Zoom in or out more than usual on Qwant Maps.
2. Copy the current web address from the browser's address bar.
3. Open another browser window in Private Browsing (Incognito mode) or a completely different browser.
4. Paste into the address bar and navigate there.

# Observed:

I get the correct place at the default zoom level.

# Expected:

Expected to have more control over what I'm linking to others and have exactly the same zoom level as when copying the address.

---

This also applies to using the Share button instead of the browser's address bar:

![image](https://user-images.githubusercontent.com/9165395/116136608-301a2300-a6db-11eb-907d-052357246335.png)

**Comment by Charlotte-Ziegler** [comment]
Hello, 
I close this issue because I think this behavior does not exist anymore.
