### ISSUE TITLE
Impossible de chercher le lycée Ampère

### ISSUE THREAD

**Issue by bristow** [Qwant/qwantmaps#146]
Bonjour,

Dans le moteur de recherche de Qwant Maps, il est impossible de chercher la chaîne suivante : lycée ampère

Il nous supprime immédiatement le terme ampère ce qui est un peu problématique.

Merci !

**Comment by amatissart** [comment]
Bonjour,

Pour bien comprendre le parcours que vous avez suivi, voici les suggestions visibles actuellement pour la requête "lycée ampère", avec une interface en français et sans être zoomé sur une région particulière (zoom < 7) :
![image](https://user-images.githubusercontent.com/4726554/119171867-7148ed00-ba65-11eb-8db8-14d030cd9499.png)

La première suggestion correspond à la recherche "lycée" à proximité de la ville d'Ampére au Brésil. La requête ayant été interprétée comme étant formulée sous la forme "catégorie + ville". J'en conviens, c'est assez peu pertinent dans ce cas précis :unamused: 
Et c'est aussi cette suggestion qui est sélectionnée lorsque la recherche est effectuée directement depuis la barre d'adresse, ou via la touche Entrée avant que les suggestions n'apparaissent.

Est-ce que c'est cette fonctionnalité qui a pu faire penser que le terme "ampère" est supprimé ?

**Comment by bristow** [comment]
En fait, les élèves (avec qui j'ai remarqué cela) n'attendent que très peu les suggestions et valident par la touche entrée immédiatement. Du coup, on se retrouve au Brésil immédiatement avec le ampère qui disparaît...
Je sais pas comment cela peut se résoudre, avec l'IP de la requête, vous pouvez pas privilégier un lycée aux alentours plutôt que d'aller au Brésil ?

Merci !

**Comment by fatal69100** [comment]
Bonjour,
En effet, cette détection n'a pas de sens. Nous avons un sujet en interne pour améliorer la pertinence de ces requêtes.
