### ISSUE TITLE
Open translations for more languages in Transifex

### ISSUE THREAD

**Issue by ticotaco72** [Qwant/qwantmaps#147]
Hello!
I would like to translate at least a bit of Qwant maps into Polish. But to do it you(project maintainers) have to accept the requested language in transifex. Over 30 languages are waiting for approval in Transifex to start translations. I have seen Polish as `requested` on Transifex over 2 weeks ago or more(similar for other languages). How are we supposed to contribute if you aren't active there? Additionally (probably depending on your Transifex configuration) you'll need to accept every new member of every translator team.

**Comment by Charlotte-Ziegler** [comment]
Hello 
I confirm that we are not using Transifex anymore.

**Comment by ticotaco72** [comment]
So how can we translate now?

**Comment by remi-dupre** [comment]
I suppose the best way would now be to open a pull request in https://github.com/Qwant/erdapfel by editing the [*.po* files](https://github.com/Qwant/erdapfel/tree/master/language/message) with poedit. (@pascaloliv @xem could probably confirm as I'm less comfortable with the process)

We do realize that this may be less convenient though, we are open to suggestions and willing to help :wink:

**Comment by xem** [comment]
Hello @ticotaco72, sorry for the delay.
Thank you for proposing your help to add Polish translations in Qwant Maps!
Unfortunately, the Web interface of Transifex is no longer useable to do this, but there's a solution:
- Clone the repository Erdapfel (https://github.com/QwantResearch/erdapfel)
- Go in the folder /language/message
- Copy en.po into a new file pl.po
- Open pl.po with a PO editor (ex: POedit: https://poedit.net/)
- Translate the strings from EN to PL

It should liik like this:

![image](https://user-images.githubusercontent.com/1225909/159718767-7caf6ae6-59ef-4465-8405-373167f6bb11.png)

Some strings have a singular form and a plural form, for example "%d room" / "%d rooms". (where %d is a number)
Contrary to English, Polish has 3 plural forms, so you also need to go in the translation properties and aff this expression to handle every plural form:

```
nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);
```

![image](https://user-images.githubusercontent.com/1225909/159720347-0dd7eb8e-f92a-4317-998b-42611d99095b.png)


Then you will see that every pluralized string will be translateable into 3 different forms. (the "1" form, then the "2/3/4" form, then the 0/5/6/7/8/9 form). Click each tab to edit the three forms.

![image](https://user-images.githubusercontent.com/1225909/159721151-e1a55da2-338c-4c94-b6e6-830e139411a2.png)

When you're done, you can open a PR.

Thank you!
