### ISSUE TITLE
Two opticians handled very differently

### ISSUE THREAD

**Issue by xeruf** [Qwant/qwantmaps#152]
Fielmann displayed as point:
https://www.qwant.com/maps/place/osm:node:635742455

Apollo as optician:
https://www.qwant.com/maps/place/osm:node:1209884803

Despite both being mapped correctly in OSM.

Furthermore, search does not yield that Fielmann at all. And in general, when my map is zoomed into Erlangen, I am confused that it shows results from Nuremberg first, often not even displaying the much closer POIs...

**Comment by bbecquet** [comment]
Hi, and thanks for your feedback!

There is actually a small OSM tagging difference between the two POIs that explains it. The Fielmann shop is correctly mapped as `shop=optician`, but also has a `healthcare=optometrist` tag.
`healthcare` has precedence over `shop` in our import system to determine the simplified class of a POI, so `shop` is ignored. But sadly `optometrist` has no full mapping to a translated name and icon, so it appears as a default point.

This kind of limitations on the class system are known, and this example will help us refine our rules.
