### ISSUE TITLE
Bad results with pathfinder in cycle mode

### ISSUE THREAD

**Issue by Naheulf** [Qwant/qwantmaps#154]
### Steps to Reproduce the Issue

1. Open Qwant map
2. Select "Directions" (itinerary)
3. Choose "By Bike" mode.
4. In `Start Point` write "Pont Tourny" and press enter
5. In `End Point` write "143 Avenue Ribot" and press enter
6. == Stop here for behavior 1 ==
7. Since the last part of the path is a long straight forward line we can move the end point on this long line (ie: on "Avenue Turgot" and "Avenue Ribot")

Note: both start and end point are in Brive-la-Gaillarde town in French.

### Expected Behavior 1

The found path should be almost straight forward (in fact in this case it should be the same as for the car mode)

### Actual Behavior 1

The found path takes a detour through the hospital.

### Expected Behavior 2

If we move the end point on the path, the global path shape should not change. Only the last part is removed

### Actual Behavior 2

Moving the end point on some sections change the beginning shape of the path.

### Debug Information

Done with Firefox 90.0 (x64) on windows 10.

Path at step 5: https://www.qwant.com/maps/routes/?mode=cycling&destination=addr%3A1.504783%3B45.164529%3A143%40143_Avenue_Ribot&origin=street%3Aosm%3Away%3A99371698%40Pont_Tourny&selected=0#map=14.16/45.1663820/1.5210605
![image](https://user-images.githubusercontent.com/14990967/126064063-bde2f3a3-384d-421b-b574-729f545ed5f3.png)

Expected path at step 5, same as car mode (behavior 1): https://www.qwant.com/maps/routes/?mode=driving&destination=addr%3A1.504783%3B45.164529%3A143%40143_Avenue_Ribot&origin=street%3Aosm%3Away%3A99371698%40Pont_Tourny&selected=0#map=14.17/45.1653460/1.5210435
![image](https://user-images.githubusercontent.com/14990967/126064144-74231481-58ae-44db-a47f-624bd11044f4.png)

A new alternative path moving the end point: https://www.qwant.com/maps/routes/?mode=cycling&destination=latlon%3A45.16528%3A1.52017&origin=street%3Aosm%3Away%3A99371698%40Pont_Tourny&selected=0#map=15.09/45.1667520/1.5288125
![image](https://user-images.githubusercontent.com/14990967/126064211-8649941b-1743-4688-8613-a9e148e24b3c.png)

The main path change to the expected path (shorter in both time and distance): https://www.qwant.com/maps/routes/?mode=cycling&destination=latlon%3A45.16559%3A1.52212&origin=street%3Aosm%3Away%3A99371698%40Pont_Tourny&selected=0#map=15.26/45.1665080/1.5297755
![image](https://user-images.githubusercontent.com/14990967/126064264-7e2782fd-d128-49f0-9069-a53d3ef75848.png)

**Comment by fatal69100** [comment]
Hi, thank you for your feedback.
Unfortunately, the result doesn't depend on our algorithm because we use the Mapbox directions API (https://docs.mapbox.com/api/navigation/directions/#routing-profiles)
