### ISSUE TITLE
Localization (Translation)

### ISSUE THREAD

**Issue by KovalevArtem** [Qwant/qwantmaps#159]
It is sad that the site is only in English - I propose to translate.
I am ready to help in the translation into **Russian**.
(For example, you can use **Weblate**, or any other service. It is completely free for open source projects.)

![image](https://user-images.githubusercontent.com/36500228/98449379-2b20e180-2144-11eb-8870-57606b640a77.png)

![image](https://user-images.githubusercontent.com/36500228/85225199-1ed7fa00-b3d8-11ea-972e-a89e573da428.png)

❗️ _This is by no means an advertisement for Weblate. In my opinion, this service is best suited for translating open-source projects, because it has open source code itself..._

**Comment by fatal69100** [comment]
Hi, thank you for your message. The site is not only in English, it depends on the language/country you set in the Qwant settings (it could be Russian). To translate, we are currently using : https://github.com/Qwant/qwantmaps/blob/master/contributing.md#translating
