### ISSUE TITLE
Qwant Maps insert in Qwant search does not immediately show OSM Attribution

### ISSUE THREAD

**Issue by Altonss** [Qwant/qwantmaps#162]
Qwant Maps insert in Qwant search does not immediately show OSM Attribution.
An interaction is required to display the attribution, but this doesn't comply with the attribution guidelines of OSM https://www.openstreetmap.org/copyright.
This issue has been tested on this url for example: https://www.qwant.com/?q=ugc+paris&t=web
Thanks!

**Comment by Altonss** [comment]
Any update on this?

**Comment by fatal69100** [comment]
Hi, thank you for your message. `For a browsable electronic map, the credit should appear in the corner of the map` : here it's a non-browsable picture map and when you click on the map, you can find OSM copyright. I am new in the team and not legal expert :sweat_smile: , we may have done this to make the small picture more readable for users. I will ask other team members if there is any reason we didn't mention copyright in this case.

**Comment by Altonss** [comment]
Thanks a lot for your answer @fatal69100 !
I will ping some people who might have an answer: @cquest @vinber :)

**Comment by vinber** [comment]
> here it's a non-browsable picture map

je cite depuis https://www.openstreetmap.org/copyright
"Sur les supports où les liens hypertextes sont impossibles (par exemple sur un support papier), nous vous suggérons de rediriger vos lecteurs vers le site openstreetmap.org (éventuellement en développant « OpenStreetMap » vers cette adresse complète) et vers opendatacommons.org."

et quand on voit l'attribution pages jaunes, j'imagine que l'on doit pouvoir trouver un petit coin pour afficher fièrement OpenStreetMap :)

![image](https://user-images.githubusercontent.com/890869/149553645-7e67744b-f23a-4a2d-8ea0-33812b9cdd57.png)

**Comment by fatal69100** [comment]
![osm_ia](https://user-images.githubusercontent.com/12247702/151204288-d3ca90b4-1e0d-4e35-8a14-84cdf3809c8a.png)
Actually, there is the credit when you click on the icone

**Comment by fatal69100** [comment]
I write the previous message because I didn't mention it before. We are working with UX to update the attribution.

**Comment by AntoninCurtit** [comment]
![image](https://user-images.githubusercontent.com/30950182/172680932-85941fd1-d5ea-45eb-a419-8b0cba696df3.png)
Crédité comme "OpenStreetMap**s**" mais toujours mieux qu'avant ;) Avec un lien vers http://www.openstreetmap.org/about/

Je considère le cas comme clos.

**Comment by AntoninCurtit** [comment]
Oups, j'ai cru que c'était le dépôt https://github.com/osm-fr/attributions/, en fait non. J'aurais du mettre plus de formes... ;) Merci pour la correction !

**Comment by Altonss** [comment]
> ![image](https://user-images.githubusercontent.com/30950182/172680932-85941fd1-d5ea-45eb-a419-8b0cba696df3.png) Crédité comme "OpenStreetMap**s**" mais toujours mieux qu'avant ;) Avec un lien vers http://www.openstreetmap.org/about/
> 
> Je considère le cas comme clos.

Pour ce qui est de "Pontarlier", cela semble correctement attribué (exepté la faute de frappe), mais pour ce qui est de https://www.qwant.com/?q=ugc+paris&t=web rien n'a changé: une interaction est toujours nécessaire

**Comment by Altonss** [comment]
I'm sorry @Charlotte-Ziegler, but I don't really consider this issue as fixed as my initial issue is still the same, nothing has changed and an interaction is still needed for https://www.qwant.com/?q=ugc+paris&t=web for example ...
