### ISSUE TITLE
Issues are left unanswered and unsolved 

### ISSUE THREAD

**Issue by norz** [Qwant/qwantmaps#165]
Is this public issue tracker still relevant, or is it abandoned and are all issues handled internally? 🤔

**Comment by fatal69100** [comment]
Hi, Qwant maps developer here. First, thank you for your interest in the project. Here is a short answer : This public issue tracker is still relevant. Also the team is small and a part of the dev team change during the past months that can explain the low development velocity. We are doing a document to summarize how we will handle issues with the roadmap and resolve/labelize the previous issues left unanswered. I hope this little communication can give you some insights.

**Comment by DaN0mic** [comment]
I imagined that the team is small and I'd liked to help. Sadly I'm not a crazy coder nor do I see a donate button anywhere, so my hands are tied in those regards. All I can do is keep translating and doing OSM I guess. It was great to hear something back and thanks for the insights, hope you will figure all out soon.

**Comment by norz** [comment]
Bonjour,

Thank you for your answer. 🙏 
Just to clarify : Qwant maps is already awesome as it is, having an efficient & pleasant rendering of Openstreetmap data. ❤️ 
The issue I wanted to open is a very minor one, so imho it’s best to leave it out for now, and patiently wait to see if you can make Qwants Maps even better. 😉 (Ratings maybe? But afaik there isn’t open data for this... 🤔) 

Have a great year! 🙏
