### ISSUE TITLE
Public transport routing and other stuff

### ISSUE THREAD

**Issue by DaN0mic** [Qwant/qwantmaps#166]
This has more or less become my summary of the most important issues right now. Since some of these are pretty old and or never have been replied to(has the project died?), I thought I mention them again. 

My intial request is close to issue #91 which was said to be implemented "as soon as possible" in 2019 and has not gotten any further updates. What I propose is a 4th option for finding routes: with public transport. I am not sure how far this is possible, because departures or any plans like that aren't in OSM data to my knowledge. 
In issue #91 tho, a map of public transport routes was requested, which is already implemented by OSM and could be very helpful. Furthermore the comments suggested showing the busline/-number for example when selecting a public transport stop, which also could be implemented with current OSM data. Public transport is coming way too short in Qwant maps, which is one of the biggest issues I'm currently facing with it and why I often resort to other services. 

On that note a dark mode/theme also would be pretty nice for your eyes. Adding turn-by-turn navigation for mobile devices requested in issue #80 also is a pretty important feature that is missing. On top of that #161 makes finding information harder and slower and decreases therefore usability. 
Issue #95, #96 and #156 also would be nice to have. 

PS: I didn't write this because i think Qwant maps is bad, but because I love it and care. <3

**Comment by Karthoo** [comment]
A possible way to implement public transport routing could be to use the [ref:IFOPT](https://wiki.openstreetmap.org/wiki/Key:ref:IFOPT) tag from OSM to connect the OSM transit stops to [public GTFS datasets](https://ptna.openstreetmap.de/gtfs/). Unfortunately the tag is not spread that widely outside central Europe, yet.

**Comment by Rik44444** [comment]
+1 for public transport routing!
