### ISSUE TITLE
Erreur adressage sur square

### ISSUE THREAD

**Issue by bristow** [Qwant/qwantmaps#169]
Bonjour,

En cherchant un square dans Qwant Maps, je suis tombé sur une adresse bizarre en 99999 :

![image](https://user-images.githubusercontent.com/1156507/151941467-fd10b317-72b3-4b44-a717-19af740a4d8a.png)

https://www.qwant.com/maps/place/osm:way:142657865?client=search-ia-maps-single#map=17.90/45.7798189/4.8251784

Ce nombre n'est pas présent dans OSM (en revanche, je viens de passer ce square en construction aujourd'hui, mais je n'ai rien supprimé concernant l'adressage).

Merci

**Comment by fatal69100** [comment]
Bonjour,
tout d'abord merci pour ton message.
Pour les adresses, on fusionne les données entre BANO https://adresse.data.gouv.fr/base-adresse-nationale/69384_2244#19/45.7796834/4.825936 et OSM https://adresse.data.gouv.fr/base-adresse-nationale/69384_2244#19/45.7796834/4.825936.
Comme on peut le constater, il manque l'information dans les deux sources de données. 
De notre côté, on va corriger ça dans un certain temps, mais si vous souhaitez avoir rapidement un correctif, vous pouvez ajouter manuellement la donnée sur l'une des deux sources pour la voir apparaitre à court terme sur Qwant maps.
