### ISSUE TITLE
Add orientation ray

### ISSUE THREAD

**Issue by Myzel394** [Qwant/qwantmaps#170]
While switching from Google Maps to Qwant Maps I realized that probably the best feature missing is **the ability to see where you're looking at**. It would be really nice if you could see this on the map, like you can on Google Maps. For a reference, take a look at this image: https://imag.malavida.com/mvimgbig/download-fs/google-maps-11908-1.jpg (pay attention to the blue ray coming out from the blue circle where you are standing).

**I can implement this feature if you would like to, I just need your ok**

**Comment by Charlotte-Ziegler** [comment]
On Qwant Maps, you can turn on the localization and see where you are using the button just above the zoom buttons. 
When this feature is activated, you can see a blue dot where you are located. 
<img width="1430" alt="Capture d’écran 2022-04-14 à 12 12 06" src="https://user-images.githubusercontent.com/54034978/163366537-cecc2f8e-c5e4-4a6a-8933-03b476818dae.png">

**Comment by Myzel394** [comment]
Yes that's correct. However, you can't see where you are looking at, which I would like to add (see my screenshot for reference)
