### ISSUE TITLE
Using external POI data

### ISSUE THREAD

**Issue by Cj-Malone** [Qwant/qwantmaps#171]
How much thought have you put into using none OSM point of interest data?

I've been producing a [data set](https://gitlab.com/KAFF/places) of shops, it's "scraped" from there websites (only when they use [structured data](https://schema.org/), and following robots.txt).

In the UK we use it as QA.
Anything in [OSM but not the list](https://osm.mathmos.net/chains/Q407009/#unexpected) is probably old OSM data.
Anything in [the list but not in OSM](https://osm.mathmos.net/chains/Q407009/#missing) is probably a shop but not mapped.

Copyright wise, it's not compatible with the ODbL, when editing OSM we need an alternative source, but I doubt any of these shops would complain if you used them as an overlay. You could probably even get explicit permission if you tried.

**Comment by sdrll** [comment]
Hi, thank you for your message. We try to simplify our own database process ad keep believing OpenStreetMap is a good poi data sources. We also use TripAdvisor in UK for some categories (hotel, restaurant, activites).

**Comment by Cj-Malone** [comment]
My dataset is now deprecated and I work on [All The Places](https://www.alltheplaces.xyz/) which does similar.

I too hope OSM POIs will become the best, I work on them daily. But currently to get the best data you'd have to conflate multiple sources like you are already doing with Tripadvisor.
