### ISSUE TITLE
Missing POIs through TripAdvisor

### ISSUE THREAD

**Issue by Itchiii** [Qwant/qwantmaps#176]
First of all, I have to say that I love Qwant and Qwant Maps in particular! As an OSM mapper, I have long wished for a map that displays POIs with relevant data and can be understood as an alternative to Google Maps.

But now to my concern. It is not really a bug but a degradation to a previous version, therefore also no feature request.

If I clicked on Restaurant or Hotel in the quick selection, some points will shown but not all of them that were originally displayed on the map. Through the partnership with TripAdvisor (which is in principle good and useful with the additional information such as reviews) are also displayed only those that are available in the database of TripAdvisor. I find that this partially hides important local businesses where an unfair distribution arises. You are indirectly asked to register the company on TripAdvisor. And I don't think that's right.

Perhaps it would be possible to have a comparison, whether the name and address in TripAdvisor are assigned, if not, the information should be obtained from OSM.

**Comment by fatal69100** [comment]
Hi Itchiii, 
thank you for your report. I, personally, really appreciate your feedback.
If you go to https://www.qwant.com/maps and press F12, the browser `Console` tab should appear => writing `localStorage.setItem('qmaps_v1_only_osm', true)` and pressing Enter should be the tricks.
I hope it helps.

**Comment by Itchiii** [comment]
Hi fatal69100, 
thanks for your reply and sorry for my late response. Unfortunately, this workaround does not solve the problem, it only restores the state, before the integration of TripAdvisor. I would still like to see a solution that displays a mixture of both. OSM as a base, TripAdvisor on top. But for for me personally it is an improvement so thanks!

**Comment by Charlotte-Ziegler** [comment]
Hi Ithchiii, 

I understand your request, however I'm sorry I don't it will be possible bfor legal reasons.
