### ISSUE TITLE
German quick access: Flughafen -> Sport

### ISSUE THREAD

**Issue by BigKananga** [Qwant/qwantmaps#190]
On German site of Qwant Maps there is a mistake in quick access (Search around this place): "Flughafen" should be "Sport" since Flughafen means airport.

![flughafen](https://user-images.githubusercontent.com/49197621/219955778-8e18c31c-c622-400f-b604-f221ce4c533f.JPG)

**Comment by sdrll** [comment]
thank you for the report, it will be fix soon : https://github.com/Qwant/erdapfel/pull/1444
