### ISSUE TITLE
Mimirsbrunn repository has gone missing?

### ISSUE THREAD

**Issue by not-my-profile** [Qwant/qwantmaps#194]
The README in this repository references https://github.com/CanalTP/mimirsbrunn multiple times but that link now leads to a 404 page. I think previously that link redirected to https://github.com/hove-io/mimirsbrunn but that's also a 404 now.

**Comment by sdrll** [comment]
Hi, it seems that Hove has closed source this repository few days ago. you can still follow our repository at https://github.com/Qwant/mimirsbrunn
