### ISSUE TITLE
Quick Access: German translation for new Eco-responsible Alternatives

### ISSUE THREAD

**Issue by BigKananga** [Qwant/qwantmaps#196]
On German site of Qwant Maps the translations of Eco-responsible Alternatives POI categories are not good:
- Sekundenzeiger -> Second Hand
- Null-Abfall - > Verpackungsfrei

For Écotables I don't know what it should mean. It mixes a lot of different types of POI. If I'd know the OSM tags that are used, I maybe could find a translation.

![eco](https://github.com/Qwant/qwantmaps/assets/49197621/ca824954-8a25-4cc0-ae00-c102c1bf6438)

**Comment by sdrll** [comment]
Hi,
thank you very much for the correction. I have changed the two translations you give. "Ecotables" is a new French label for ecological restaurant. Unfortunately, we didn't implement a custom menu depending on the user country… I will take a look to this issue.

**Comment by BigKananga** [comment]
Here in Germany "Ecotables" shows bus stations, train stations, schools, attactions, churches and so on. This doesn't make sense of course. I think for most users this is very confusing.

**Comment by sdrll** [comment]
I didn't expect that :grimacing: I am going to fix this issue

**Comment by sdrll** [comment]
Should be fixed

**Comment by BigKananga** [comment]
Thanks, now works as intended. :)

**Comment by BigKananga** [comment]
There are 2 new mistakes in German translation:
Ohne Wrapper -> Verpackungsfrei
Second Hand" -> the " should be removed

**Comment by BigKananga** [comment]
Last comment is still up to date

**Comment by sdrll** [comment]
Should be done
