### ISSUE TITLE
Why are opening hours for POIs not shown anymore?

### ISSUE THREAD

**Issue by sfkeller** [Qwant/qwantmaps#199]
Why are opening hours for POIs (e.g. restaurants, shops) not shown anymore?

See e.g. https://www.qwant.com/maps/place/osm:node:1355269805@Dieci_Restaurant 

I'm sure that a few weeks ago opening hours have been shown for POIs. 
This was a unique selling point for using Qwant maps!

--Stefan

**Comment by sfkeller** [comment]
I really wonder what the reason could be to abolish this USP again? Here in Switzerland we are busy recording more opening hours. See https://potm.osm.ch/superset/dashboard/33/

**Comment by sdrll** [comment]
Thank you for reporting this issue. We will try to fix the issue as soon as possible.

**Comment by sfkeller** [comment]
Excellent ! Aujourd'hui est un (autre) bon jour pour OpenStreetMap :-)
