### ISSUE TITLE
amenity=community_centre doesn't display website and contact information

### ISSUE THREAD

**Issue by imagoiq** [Qwant/qwantmaps#200]
Amenity=community_centre only show address meta information, but no contact information.

Example:

https://www.qwant.com/maps/place/osm:way:44787287@Centre_Pluriculturel_et_social_dOuchy#map=16.50/46.5110308/6.6303810
https://www.openstreetmap.org/way/44787287#map=18/46.51098/6.63112

https://www.qwant.com/maps/place/osm:way:45780921@Maison_de_Quartier_Sous-Gare#map=17.45/46.5153284/6.6263358
https://www.openstreetmap.org/way/45780921

https://www.qwant.com/maps/place/osm:node:4574913693@Centre_social_et_culturel_Rosa-Parks#map=16.50/48.8982464/2.3715259
https://www.openstreetmap.org/node/4574913693

**Comment by sdrll** [comment]
Thank you for reporting the bug. We are resolving the issue.

**Comment by sdrll** [comment]
Should be good
