### ISSUE TITLE
Display fax number

### ISSUE THREAD

**Issue by Postit2019** [Qwant/qwantmaps#36]
Unfortunately, only the telephone number is displayed.
Is it possible to add the fax number?

contact:fax 

and

fax=*

**Comment by jbgriesner** [comment]
Thanks for this suggestion.
We'll consider to add this information soon, even if we are not sure the if the fax is still the most widely spread way to communicate ^^

**Comment by Postit2019** [comment]
There are many institutions that still use a fax, e.g. hospitals, public institutions, banks, schools.
It is no longer widely used, but still in use.
