### ISSUE TITLE
Location not found on Qwant Maps, OK in OSM.

### ISSUE THREAD

**Issue by maat-ieu** [Qwant/qwantmaps#61]
Hi all, 

I had tested my home address, it do not show into Qwant Maps beta at this time. I had checked in OSM, the place is present.
Please look at attached print screens to see those differences.
Greetings, 
Mathieu
<img width="543" alt="2019-06-27 12_13_13-Qwant Maps- Beta" src="https://user-images.githubusercontent.com/33928877/60259340-54d2c300-98d7-11e9-963b-ddb5d5f8c9db.png">
<img width="386" alt="2019-06-27 12_31_00-OpenStreetMap" src="https://user-images.githubusercontent.com/33928877/60259431-86e42500-98d7-11e9-9413-d1255aea10f8.png">

**Comment by zorglubu** [comment]
Yes. Nodes with tag place=village or place=hamlet seem not being searched.

**Comment by Sigmun** [comment]
The same for building or area tags. Qwant maps seems to search only on POI
![Capture d'écran de 2019-07-01 09-19-13](https://user-images.githubusercontent.com/396437/60417787-974f1500-9be1-11e9-95fb-2472e97caeed.png)
![Capture d'écran de 2019-07-01 09-20-18](https://user-images.githubusercontent.com/396437/60417794-99b16f00-9be1-11e9-96b0-8df9465dd768.png)

**Comment by Charlotte-Ziegler** [comment]
This issue has been resolved :-)
