### ISSUE TITLE
Pinpoints the wrong place for a town, using the centre of a boundary rather than a place node

### ISSUE THREAD

**Issue by chris-morgan** [Qwant/qwantmaps#65]
I searched for the town I live in, Navarre, VIC, Australia, and got given https://www.qwant.com/maps/place/admin:osm:relation:3100287@Navarre. It drops a pin in quite the wrong place, almost 20km away from where the town of Navarre actually is.

Compare this with https://www.openstreetmap.org/relation/3100287, and you see the problem: it’s selecting what looks to be the centre of a rather large *boundary*; however, the logical place to call “Navarre” is actually close to the southern extremity of that boundary.

(I may say that the OSM data is actually wrong and fairly irrelevant for Navarre: it’s using the 2011 census boundary rather than the much smaller 2016 boundary, but citing the 2016 population. And the census boundaries are different from the actual administrative suburb boundaries. But that’s an OSM issue rather than a Qwant Maps issue. I should look into updating all of that myself.)

I think there are then two issues:

1. It should have drawn the outline of the boundary, rather than dropping a pin at what is effectively an arbitrary location inside the boundary.

2. I think it should have surfaced [node 283289063](https://www.openstreetmap.org/node/283289063)  (place = village, name = "Navarre", is_in = "Victoria, Australia"), rather than the administrative boundary. (Incidentally, we don’t use council names in Australia as part of addresses, so we’d never mention the shire part present in “Navarre, Shire of Northern Grampians, Victoria, Australia”.)

(For your amusement, Google Maps gets Navarre wrong too, [drawing it about 4km south of the town](https://www.google.com/maps/place/Navarre+VIC+3384), and I’ve tried to get them to fix it on at least six occasions by at least three means, all unsuccessfully so far.)

**Comment by spantaleev** [comment]
I was just about to report the same issue, but had trouble figuring out what exactly is going on.
Thankfully, I can just join in on your great research with another test case!

A search for some (random) city in Bulgaria (e.g. "Radomir") yields [this](https://www.qwant.com/maps/place/admin:osm:relation:1978291@Radomir#map=11.00/42.4827195/22.9450534).

The search result suggestion is reported as a city, but when positioning the marker it seems to be going one level up, to the administrative boundary that the city is in.. and then using the center of that as the marker. It's clearly off. The city is much further north than that, as you can see from the screenshot:

![qwant-maps-bulgaria-radomir-city-marker](https://user-images.githubusercontent.com/388669/60380300-2b877380-9a4c-11e9-8161-bf97177b2713.png)

**Comment by antoine-de** [comment]
Hi, thanks for the issue!

qwant map uses [cosmogony](http://cosmogony.world) under the hood to understand the administrative regions around the world.

cosmogony use [libpostal's rules](https://github.com/openvenues/libpostal/blob/master/resources/boundaries/osm/au.yaml) to understand how the administrative regions are mapped in OSM.

The Australian rules in lib postal does not not seems ok (but reading the [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag%3aboundary=administrative) I'm not sure which level should be used for cities in Australia)

If I have a look in cosmogony in [Australia](http://cosmogony.world/#/10.80/143.12/-36.91) or [Bulgaria](http://cosmogony.world/#/12.64/22.99/42.55) I don't really understand how we could improve libpostal rules for those countries. (click on the left bar of cosmogony to change the admin level selection)

In you have insight on those, feel free to contribute you local knowledge to [libpostal](https://github.com/openvenues/libpostal), [cosmogony](https://github.com/osm-without-borders/cosmogony/)  or directly to OSM, It's very difficult to know the right mapping without precise local knowledge.

**Comment by Charlotte-Ziegler** [comment]
This issue has been resolved :-)
