### ISSUE TITLE
Stop using Pages Jaunes

### ISSUE THREAD

**Issue by bristow** [Qwant/qwantmaps#68]
My title is deliberately provocative, I explain.

In my neighbourhood, I correctly located the restaurants in OpenStreetMap:

http://pix.toile-libre.org/upload/original/1561810195.png

In Qwant Maps, if I click on the new Restaurant button, restaurants disappear (Le petit ours gourmand) and some become misplaced (examples: Miwam, O'comptoir)

http://pix.toile-libre.org/upload/original/1561810229.png

It would also be desirable:
- stop using Yellow Pages
- either making a mix of the 2 databases

Thank you in advance!

**Comment by bristow** [comment]
Another possible alternative. Use the Masq profile to select the data that would be displayed (OSM or Yellow Pages)

**Comment by Bibi56** [comment]
Third alternative: use OSM POI if it exists. Use only Pages Jaunes if OSM don't have the equivalent. For Pages Jaunes POI, refuse to display them if too close to the railway and highway networks and send the POI list where geocoding is bad back to Pages Jaunes.

**Comment by bristow** [comment]
No label WIP ?

:)

**Comment by jbgriesner** [comment]
"Soon"... :)

**Comment by zorglubu** [comment]
I had the same problem : when clicking on one of the buttons "Les services Qwant Maps", the locations change or the POI's disappear and data like opening hours become unavailable (OSM POI's are hidden). And I thought it was a bug -> **bad user experience**.

I understand that many data (phone, picture, opening hours, stars...) are available on Pages Jaunes for France, but location is rather bad :-) .
If a partenariat is really a plus for Qwant, it should be more clear that there are two different displays on the map : one coming from openstreetmap, another one coming from Pages Jaunes.

**Comment by Bibi56** [comment]
> "Soon"... :)

I may have a different understanding of "soon" :-(.

**Comment by i-need-to-tell-you-something** [comment]
Speaking of confusing user experience - in Estonia and in London I get nothing when I enable the <kbd>Services</kbd> filter. 
![image](https://user-images.githubusercontent.com/9165395/116132785-a0727580-a6d6-11eb-8c40-248ef58877aa.png)
