### ISSUE TITLE
Addresses founds not relevant when street name is too a city name

### ISSUE THREAD

**Issue by Stephane99** [Qwant/qwantmaps#82]
I am looking for "11 Avenue du Tremblay, 75012 Paris".

I begin to fill "11 Avenue du Tremblay" (number and name of the street)
=> This street is not in the results:
"11 avenue du Havre" to "Tremblay-en-France, France"
"11 avenue du Dauphiné" in "Tremblay-en-France, France"
...
All streets belong to the city "Tremblay-En-France", none of the streets returned bears the name of street "Tremblay"!

Second try, I add the postal code: "11 Avenue du Tremblay, 75012"
=> Same results

Third test, I add the name of the city: "11 Avenue du Tremblay, 75012 Paris"
=> OK, the street is well found.

**Comment by jbgriesner** [comment]
Thanks for this feedback.
The problem is due to the absence of this address either in OSM and BANO source.
If you want to see this address you can add it into OSM: https://wiki.openstreetmap.org/wiki/Key:addr

Also we are working on a system to provide us this feedback directly into Qwant Maps :)
